name: Check & Deploy Backend

on: 
  push:
    branches:
      - dev
      - main

jobs:
  tests-and-format:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: vibik_test
          POSTGRES_USER: vibik_user
          POSTGRES_PASSWORD: vibik_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U vibik_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release
      
      - name: Run tests
        env:
          POSTGRES_DB: vibik_test
          POSTGRES_USER: vibik_user
          POSTGRES_PASSWORD: vibik_pass
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Dotnet format whitespace (fix)
        run: dotnet format whitespace

      - name: Dotnet format verify
        run: dotnet format --verify-no-changes

  build-docker:
    runs-on: ubuntu-latest
    needs: tests-and-format

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -f Api/Dockerfile -t vibik-api .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push docker image
        run: |
            docker tag vibik-api jlychee/vibik-api:latest
            docker push jlychee/vibik-api:latest

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Deploy to DEV server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          passphrase: ${{ secrets.DEV_SERVER_SSH_PASSPHRASE }}
          script: |
            cd vibik
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Deploy to PROD server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd vibik
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d
